apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ylapi.fullname" . }}
  labels:
    {{- include "ylapi.labels" . | nindent 4 }}
data:
  main.py: |
    from fastapi import FastAPI
    import os

    app = FastAPI()

    @app.get("/")
    def read_root():
        return {"Hello": f"password: {os.environ.get('PASSWORD')}"}

    @app.get("/hello/{user}")
    def hello(user: str):
        return {"Hello": user}

    @app.get("/world/{user}")
    def hello(user: str):
        return {"World": user}    

    @app.get("/www/{user}")
    def hello(user: str):
        return {"www": user}    
