apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ylapi.fullname" . }}
  labels:
    {{- include "ylapi.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum  10 | b64enc }}
