{{- $fullname := include "ylapi.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "ylapi.labels" . | nindent 4 }}
type: Opaque
data:
  # Generate secret password or retrieve one if already created.
  # https://github.com/bitnami/charts/blob/07062ee01382e24b8204b27083ff3e8102110c2f/bitnami/common/templates/_secrets.tpl#L66-L142
  password: {{ include "common.secrets.passwords.manage" (dict "secret" $fullname "key" "password" "providedValues" (list "secrets.password" ) "length" 10 "strong" false "chartName" "chartName" "context" $) }}
